name: Deploy to Google App Engine
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.x ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.JS ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version}}

      - name: Install
        run: |
          yarn install

      - name: Build
        run: |
          yarn run build --if-present
        env:
          REACT_APP_GRAPHQL_HTTP_ENDPOINT: ${{ secrets.GRAPHQL_HTTP_ENDPOINT }}
          REACT_APP_GRAPHQL_WS_ENDPOINT: ${{ secrets.GRAPHQL_WS_ENDPOINT }}
          REACT_APP_GRAPHQL_SECRET: ${{ secrets.GRAPHQL_SECRET }}
          CI: false

      - name: Deploy
        id: deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          deliverables: ./app.yml
          credentials: ${{ secrets.GCP_SA_KEY }}
